[backends]
[backends.gatecounter]
    [backends.gatecounter.servers.gatecounter-server]
    url = "http://grafana:3000"
[frontends]
[frontends.gatecounter]
entryPoints = ["http"]
backend = "gatecounter"
    [frontends.gatecounter.routes.test]
    rule = "HostRegexp:grafana.{hostname:[a-z]+}{suffix:(\.local|\.home)}"